CONTROLLER_PRESETS = {
    "Xbox": [
        "A",
        "B",
        "X",
        "Y",
        "LB",
        "RB",
        "LT",
        "RT",
        "LS",
        "RS",
        "D-Pad Up",
        "D-Pad Down",
        "D-Pad Left",
        "D-Pad Right",
        "Start",
        "Back",
        "Guide",
        "Left Stick Up",
        "Left Stick Down",
        "Left Stick Left",
        "Left Stick Right",
        "Right Stick Up",
        "Right Stick Down",
        "Right Stick Left",
        "Right Stick Right",
    ],
    "PlayStation": [
        "Cross",
        "Circle",
        "Square",
        "Triangle",
        "L1",
        "R1",
        "L2",
        "R2",
        "L3",
        "R3",
        "D-Pad Up",
        "D-Pad Down",
        "D-Pad Left",
        "D-Pad Right",
        "Options",
        "Create",
        "PS",
        "Left Stick Up",
        "Left Stick Down",
        "Left Stick Left",
        "Left Stick Right",
        "Right Stick Up",
        "Right Stick Down",
        "Right Stick Left",
        "Right Stick Right",
    ],
    "Nintendo": [
        "A",
        "B",
        "X",
        "Y",
        "L",
        "R",
        "ZL",
        "ZR",
        "Left Stick",
        "Right Stick",
        "D-Pad Up",
        "D-Pad Down",
        "D-Pad Left",
        "D-Pad Right",
        "Plus",
        "Minus",
        "Home",
        "Capture",
        "Left Stick Up",
        "Left Stick Down",
        "Left Stick Left",
        "Left Stick Right",
        "Right Stick Up",
        "Right Stick Down",
        "Right Stick Left",
        "Right Stick Right",
    ],
}

DEFAULT_INPUTS = [
    "SPACE",
    "CTRL",
    "E",
    "R",
    "Q",
    "F",
    "MOUSE_LEFT",
    "MOUSE_RIGHT",
    "SHIFT",
    "C",
    "UP",
    "DOWN",
    "LEFT",
    "RIGHT",
    "ENTER",
    "TAB",
    "F8",
    "W",
    "S",
    "A",
    "D",
    "MOUSE_UP",
    "MOUSE_DOWN",
    "MOUSE_LEFT_MOVE",
    "MOUSE_RIGHT_MOVE",
]


def criar_botoes_padrao(padrao):
    return [
        {
            "nome": acao,
            "entrada": entrada,
            "acao": acao,
        }
        for entrada, acao in zip(DEFAULT_INPUTS, botoes_do_padrao(padrao))
    ]


def botoes_do_padrao(padrao):
    return CONTROLLER_PRESETS.get(padrao, CONTROLLER_PRESETS["Xbox"])
